# v1.3.0 October 26, 2013
# https://github.com/bevry/base
language: node_js
install: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travisci@bevry.me